version: "3.8"
services:
  overbyte-websocket:
    build: .
    container_name: overbyte-websocket
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./replays:/app/replays
    # Uncomment if you want to use a custom .env file
    # environment:
    #   - PORT=3000
